_wandb:
    value:
        cli_version: 0.23.1
        e:
            24149uemhaipapl26msyp6kvqojumttf:
                apple:
                    ecpuCores: 2
                    gpuCores: 32
                    memoryGb: 64
                    name: Apple M1 Max
                    pcpuCores: 8
                    ramTotalBytes: "68719476736"
                    swapTotalBytes: "12884901888"
                args:
                    - max_steps=100
                    - batch_size=1
                    - group_size=4
                    - max_tokens=128
                    - max_shards=10
                    - load_checkpoint_path=tinker://93aa6903-4d94-5f18-9eae-11a0b1e564f9:train:0/weights/final
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "1995218165760"
                        used: "1880157036544"
                email: git@sdan.cc
                executable: /Users/sdan/Developer/geospot-vlm/.venv/bin/python3
                git:
                    commit: e8856c2bdf3f865d49413aa0f765c6fb6f9678ef
                    remote: https://github.com/sdan/geospot-vlm.git
                host: sdan
                memory:
                    total: "68719476736"
                os: macOS-15.6.1-arm64-arm-64bit
                program: -m geospot.train
                python: CPython 3.12.10
                root: /Users/sdan/Developer/geospot-vlm
                startedAt: "2025-12-15T09:26:58.923560Z"
                writerId: 24149uemhaipapl26msyp6kvqojumttf
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 11
                - 49
                - 51
            "3":
                - 16
            "4": 3.12.10
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 1
coord_reward_kind:
    value: exp
coord_tau_end:
    value: 25
coord_tau_start:
    value: 2000
coord_weight:
    value: 0.7
geocell_weight:
    value: 0.3
geohash_precision:
    value: 5
group_size:
    value: 4
learning_rate:
    value: 4e-05
max_tokens:
    value: 128
model_name:
    value: Qwen/Qwen3-VL-235B-A22B-Instruct
use_tau_schedule:
    value: true
